function	imgui(hfig,siz)

% Adds image adjustment sliders to a figure.
%
% imgui(hfig) adds sliders to the figure with handle hfig.  
% imgui(hfig,siz) adds slides a fraction siz of the total figure height to the figure with handle hfig.
% imgui without arguments adds sliders to the current figure.
% 
% Sliders are used to control inputs to the imadjust function.
% The slider on the left  controls brightness factor gamma 
% (up = darker, down = brighter),
% while the sliders on the right control thresholding 
% (inner = top, outer = bottom).  
% To omit the sliders from figure printouts, use the print -noui option.
%
% Daniel K. Sodickson 8/11/98

if nargin < 1,
   hfig = gcf;
   siz = 0.98;
elseif nargin < 2,	% DKS 2/2/2000
   siz = 0.98;
end

figure(hfig)
map = get(hfig,'colormap');
set(hfig,'UserData',map);
hgam = uicontrol(...  
                'BackgroundColor',[0.7 0.7 0.7 ],...  
                'CallBack',...
	['gamma = get(findobj(gcbf,''Tag'',''slider_gamma''),''Value'');'... 
	 'high = get(findobj(gcbf,''Tag'',''slider_high''),''Value'');'...
	 'low = get(findobj(gcbf,''Tag'',''slider_low''),''Value'');'...
	 'low = min([low high-eps]);'...
	 'set(findobj(gcbf,''Tag'',''slider_low''),''Value'',max([low 0]));'...
	 'map = imadjust(get(gcbf,''UserData''),[low high],[],gamma);'... 	
	 'set(gcbf,''Colormap'',map);'],...  
                'ForegroundColor',[0 0 0 ],...  
                'Units','normalized',...  
                'Position',[0.01 0.01 0.025 siz ],...  
                'String',' ',...  
                'Style','slider',...  
		'Min',0,... 
		'Max',2,... 
		'Value',1,... 
                'Visible','on',...  
                'Tag',['slider_gamma']);  
hhigh = uicontrol(...  
                'BackgroundColor',[0.7 0.7 0.7 ],...  
                'CallBack',...
	['gamma = get(findobj(gcbf,''Tag'',''slider_gamma''),''Value'');'... 
	 'high = get(findobj(gcbf,''Tag'',''slider_high''),''Value'');'...
	 'low = get(findobj(gcbf,''Tag'',''slider_low''),''Value'');'...
	 'low = min([low high-eps]);'...
	 'set(findobj(gcbf,''Tag'',''slider_low''),''Value'',max([low 0]));'...
	 'map = imadjust(get(gcbf,''UserData''),[low high],[],gamma);'... 	
	 'set(gcbf,''Colormap'',map);'],...  
                'ForegroundColor',[0 0 0 ],...  
                'Units','normalized',...  
                'Position',[0.94 0.01 0.025 siz ],...  
                'String',' ',...  
                'Style','slider',...  
		'Min',0,... 
		'Max',1,... 
		'Value',1,... 
                'Visible','on',...  
                'Tag',['slider_high']); 
hlow = uicontrol(...  
                'BackgroundColor',[0.7 0.7 0.7 ],...  
                'CallBack',...
	['gamma = get(findobj(gcbf,''Tag'',''slider_gamma''),''Value'');'... 
	 'high = get(findobj(gcbf,''Tag'',''slider_high''),''Value'');'...
	 'low = get(findobj(gcbf,''Tag'',''slider_low''),''Value'');'...
	 'low = min([low high-eps]);'...
	 'set(findobj(gcbf,''Tag'',''slider_low''),''Value'',max([low 0]));'...
	 'map = imadjust(get(gcbf,''UserData''),[low high],[],gamma);'... 	
	 'set(gcbf,''Colormap'',map);'],...  
                'ForegroundColor',[0 0 0 ],...  
                'Units','normalized',...  
                'Position',[0.965 0.01 0.025 siz ],...  
                'String',' ',...  
                'Style','slider',...  
		'Min',0,... 
		'Max',1,... 
		'Value',0,... 
                'Visible','on',...  
                'Tag',['slider_low']); 
